version: "3.8"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: register-clients-api
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - mongodb

  mongodb:
    image: "mongo:6.0.2"
    container_name: mongodb-con
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=kenlo
    volumes:
      - .docker/dbdata/mongodb:/data/db
    expose:
      - "27017"
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
        - ME_CONFIG_MONGODB_SERVER=mongodb
        - ME_CONFIG_MONGODB_AUTH_USERNAME=user
        - ME_CONFIG_MONGODB_AUTH_PASSWORD=password
        - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
        - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    depends_on:
      - mongodb