swagger: '2.0'
info:
  title: Kenlo test API Gateway
  description: Serviços de cadastro de potenciais clientes e integração com o ChatGPT para o teste da Kenlo
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:                              
  /clients:
    post:
      tags:
        - clients
      summary: Cadastra um potencial cliente
      operationId: PostClients
      parameters:
        - in: body
          name: client
          description: Potencial cliente
          schema:
            type: object
            required:
              - name
              - email
              - phoneNumber
            properties:
              name:
                type: string
                example: Fulano
              email:
                type: string
                example: fulano@email.com
              phoneNumber:
                type: string
                example: 13998876655
      x-google-backend:             
        address: https://register-clients-api-daq6rtxxca-uc.a.run.app/clients
      responses:
        201:
          description: Potencial cliente criado com sucesso
          schema:
            type: object
            properties:
              _id:
                type: string
                example: 6467f4b1814cc36532fc67be
              name:
                type: string
                example: Fulano
              email:
                type: string
                example: fulano@email.com
              phoneNumber:
                type: string
                example: 13998876655
              __v:
                type: integer
                example: 0
                  
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/InternalServerError'
        400:
          description: Invalid Request
          schema:
            $ref: '#/definitions/BadRequest'
    get:
      tags:
        - clients
      summary: Retorna os clientes cadastrados
      operationId: GetClients
      x-google-backend:             
        address: https://register-clients-api-daq6rtxxca-uc.a.run.app/clients
      responses:
        200:
          description: Potencial cliente criado com sucesso
          schema:
            type: object
            properties:
              clients:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      example: 6467f4b1814cc36532fc67be
                    name:
                      type: string
                      example: Fulano
                    email:
                      type: string
                      example: fulano@email.com
                    phoneNumber:
                      type: string
                      example: 13998876655
                  
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/InternalServerError'
  
  /interactions:
    post:
      tags:
        - interactions
      summary: Cadastra uma interação com o ChatGPT
      operationId: PostInteractions
      parameters:
        - in: body
          name: interaction
          description: A pergunta para o ChatGPT
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
      x-google-backend:             
        address: https://chatgpt-integration-api-daq6rtxxca-uc.a.run.app/questions
      responses:
        201:
          description: Interação criada com sucesso
          schema:
            type: object
            properties:
              _id:
                type: string
                example: 6467f4b1814cc36532fc67be
              message:
                type: string
                example: This is a ChatGPT interaction
              answer:
                type: string
                example: This is a ChatGPT interaction response
              __v:
                type: integer
                example: 0
                  
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/InternalServerError'
        503:
          description: Service Unavailable
          schema:
            type: object
            properties:
              _id:
                type: string
                example: 6467f4b1814cc36532fc67be
              message:
                type: string
                example: This is a ChatGPT interaction
              answer:
                type: string
                example: This is a ChatGPT interaction response
              __v:
                type: integer
                example: 0
        400:
          description: Invalid Request
          schema:
            $ref: '#/definitions/BadRequest'
    get:
      tags:
        - interactions
      summary: Retorna as interações feitas com o ChatGPT
      operationId: GetInteractions
      #actual address of the cloud function where the request is supposed to be forwarded
      x-google-backend:             
        address: https://chatgpt-integration-api-daq6rtxxca-uc.a.run.app/questions
      responses:
        200:
          description: ChatGPT Interaction
          schema:
            type: object
            properties:
              interactions:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      example: 6467f4b1814cc36532fc67be
                    message:
                      type: string
                      example: ChatGPT question
                    answer:
                      type: string
                      example: ChatGPT answer
                  
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/InternalServerError'
  
definitions:
  InternalServerError:
    properties:   
      statusCode:
        type: number
        example: 500
      message:
        type: string
        example: 'Error code: 1100'
      error:
        type: string
        example: Internal Server Error
  BadRequest:
    properties:   
      statusCode:
        type: number
        example: 400
      message:
        type: array
        items:
          type: string
          example: field must not be empty.
      error:
        type: string
        example: Bad Request