swagger: '2.0'
info:
  title: Kenlo Register Clients API
  description: Uma API que recebe dados de potenciais clientes e armazena em um banco de dados NoSQL (MongoDB)
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:                              
  /clients:
    post:
      tags:
        - clients
      summary: Cadastra um potencial cliente
      operationId: PostClients
      parameters:
        - in: body
          name: client
          description: Potencial cliente
          schema:
            type: object
            required:
              - name
              - email
              - phoneNumber
            properties:
              name:
                type: string
                example: Fulano
              email:
                type: string
                example: fulano@email.com
              phoneNumber:
                type: string
                example: 13998876655
      responses:
        201:
          description: Potencial cliente criado com sucesso
          schema:
            type: object
            properties:
              _id:
                type: string
                example: 6467f4b1814cc36532fc67be
              name:
                type: string
                example: Fulano
              email:
                type: string
                example: fulano@email.com
              phoneNumber:
                type: string
                example: 13998876655
              __v:
                type: integer
                example: 0
                  
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/InternalServerError'
        400:
          description: Invalid Request
          schema:
            $ref: '#/definitions/BadRequest'
    get:
      tags:
        - clients
      summary: Retorna os clientes cadastrados
      operationId: GetClients
      x-google-backend:             
        address: https://register-clients-api-daq6rtxxca-uc.a.run.app/clients
      responses:
        200:
          description: Potencial cliente criado com sucesso
          schema:
            type: object
            properties:
              clients:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      example: 6467f4b1814cc36532fc67be
                    name:
                      type: string
                      example: Fulano
                    email:
                      type: string
                      example: fulano@email.com
                    phoneNumber:
                      type: string
                      example: 13998876655
                  
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/InternalServerError'
  
definitions:
  InternalServerError:
    properties:   
      statusCode:
        type: number
        example: 500
      message:
        type: string
        example: 'Error code: 1100'
      error:
        type: string
        example: Internal Server Error
  BadRequest:
    properties:   
      statusCode:
        type: number
        example: 400
      message:
        type: array
        items:
          type: string
          example: field must not be empty.
      error:
        type: string
        example: Bad Request